import Footer from "./components/footer/footer";
import Header from "./components/header/Header";
import "./globals.css";
import Head from 'next/head';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};

export default  function RootLayout({ children }) {

  return (
    
          <>
           <Head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                {/* Другие мета-теги и метаданные */}
              </Head>
              <Header />
              <main>{children}</main>
              <Footer />
   
          </>
  );
}
