
import Footer from "./components/footer/footer";
import Header from "./components/header/Header";
import "./globals.css";
import { useTranslation } from 'next-export-i18n';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};

export default function RootLayout({ children, locale }) {
  const { t } = useTranslation();

  return (
    <html lang={locale}>
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
