import Footer from "./components/footer/footer";
import Header from "./components/header/Header";
import "./globals.css";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import nextI18nextConfig from '../../next-i18next.config';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};


export default function RootLayout({ children }) {

  return (
    <html lang="">
      <body>
        <Header />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


export async function getServerSideProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'], nextI18nextConfig)),
      title: 'products',
      description: 'products_description',
    },
  };
}