import { I18nextProvider } from "react-i18next";
import Footer from "./components/footer/footer";
import Header from "./components/header/Header";
import "./globals.css";
import i18n from "../../i18n";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};


export default function RootLayout({ children }) {

  return (
   
      <html lang="">
      <body>
        <Header />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>

    
  );
}
