
import Polygraphy from './Poligrafy';

export const metadata = {
    title: "Prod title",
    description: "Generated by create next "
  };



export default function Page() {
    return <Polygraphy />
}