import { NextIntlClientProvider } from "next-intl";
import Footer from "./components/footer/footer";
import Header from "./components/header/Header";




import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};

async function getMessages(locale) {
  try {
    return (await import(`../../lang/${locale}.json`)).default
  } catch (error) {
    console.log(error);
  }
}

export async function generateStaticParams() {
  return ['az', 'ru'].map((locale) => ({ locale }))
}


export default async  function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages(locale)


  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider locale={locale} messages={messages}>

          <Header lang={locale} />
          <main>
            {children}
          </main>
          <Footer />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
