import Footer from "./components/footer/footer";
import Header from "./components/header/Header";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};

const locales = ['az', 'ru'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default async  function RootLayout({ children , params: {locale}}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>

          <Header />
          <main>
            {children}
          </main>
          <Footer />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
