import { NextIntlClientProvider } from "next-intl";
import Header from "./components/header/Header";
import {getMessages} from 'next-intl/server';
import "./globals.css";
import FilterCategory from "./prod/FilterCategory";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};




export default async  function RootLayout({ children, params: { locale } }) {

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider  messages={messages}>

          <Header  />
     
          <main>
            {children}
          </main>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
