import Footer from "./components/footer/footer";
import Header from "./components/header/Header";

import {NextIntlClientProvider} from 'next-intl';
import {unstable_setRequestLocale} from 'next-intl/server';


import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};

async function getMessages(locale){
  try {
    return (await import(`../../../lang/${locale}.json`)).default
  } catch (error) {
    console.log(error);
  }
}

export async function generateStaticParams(){
  return ['az', 'ru'].map(locale => ({locale}))
}

export default async  function RootLayout({ children,
  params }) {
    const messages = await getMessages(params.locale);
    unstable_setRequestLocale(params.locale)
  return (
    <html lang={params.locale}>
      <body>
      <NextIntlClientProvider locale={params.locale}  messages={messages}>

          <Header  />
          <main>
            {children}
          </main>
          <Footer />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
