import Footer from "./components/footer/footer";
import Header from "./components/header/Header";

import {unstable_setRequestLocale} from 'next-intl/server';
import {getTranslations} from 'next-intl/server';

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};


const locales = ['az', 'ru'];
 
export function async generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default async  function RootLayout({ children,
  params: {locale} }) {
    unstable_setRequestLocale(locale);
    let t = await  getTranslations();
    console.log(t);

  return (
    <html lang={locale}>
      <body>

          <Header lang={locale} t={t} />
          <main>
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
