import { NextIntlClientProvider } from "next-intl";
import Header from "./components/header/Header";

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};




export default async  function RootLayout({ children, params: { locale } }) {


  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>

          <Header lang={locale} />
          <main>
            {children}
          </main>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
