import Footer from "./components/footer/footer";
import Header from "./components/header/Header";

import {NextIntlClientProvider} from 'next-intl';
import {unstable_setRequestLocale} from 'next-intl/server';


import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next "
};


const locales = ['az', 'ru'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default async  function RootLayout({ children,
  params: {locale} }) {
    

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>

          <Header lang={locale} />
          <main>
            {children}
          </main>
          <Footer />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
